"""
CFB ANALYTICS
validate_training_table_2025.py

SEALED 2025 evaluation using the audited SportsDataverse canonical historical
training table.

Outer split:
    TRAIN = 2019-2024
    TEST  = 2025

Rules:
- No API calls.
- 2025 is never used to choose alpha, ridge strength, feature transforms,
  residual scale, or probability calibration.
- Alpha is selected by rolling inner OOS validation contained entirely inside
  2019-2024.
- Market spread is evaluation-only and never appears in predictive features.
- This evaluates a same-dataset linear margin CONTROL against a modular
  two-team SCORE ENGINE. It does NOT claim to reproduce the exact current
  production SP+/HFA model because those inputs are not in this historical
  SportsDataverse table.

Reads:
    data/training/historical_games.csv
    data/training/historical_training_audit.json

Writes:
    data/training/sealed_2025_score_engine.json
"""

from __future__ import annotations

import json
import math
from pathlib import Path

import numpy as np
import pandas as pd


ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data" / "training" / "historical_games.csv"
AUDIT = ROOT / "data" / "training" / "historical_training_audit.json"
OUT = ROOT / "data" / "training" / "sealed_2025_score_engine.json"

TRAIN_YEARS = list(range(2019, 2025))
TEST_YEAR = 2025

RIDGE_LAMBDA = 2.0
ALPHA_CANDIDATES = [1.25, 1.50, 1.75, 2.00, 2.25, 2.50]

# Core football metrics available both as previous-season priors and
# same-season pregame values in the canonical table.
METRICS = [
    "off_epa",
    "off_success_rate",
    "off_explosive_rate",
    "off_pass_epa",
    "off_rush_epa",
    "havoc_allowed_rate",
    "line_yards_per_rush",
    "scoring_opp_rate",
    "drives",
    "plays_per_drive",
    "def_epa_allowed",
    "def_success_allowed",
    "def_explosive_allowed",
    "def_pass_epa_allowed",
    "def_rush_epa_allowed",
    "def_havoc_created_rate",
    "def_line_yards_allowed",
    "def_scoring_opp_allowed",
]

RATE_METRICS = {
    "off_success_rate",
    "off_explosive_rate",
    "havoc_allowed_rate",
    "scoring_opp_rate",
    "def_success_allowed",
    "def_explosive_allowed",
    "def_havoc_created_rate",
    "def_scoring_opp_allowed",
}


def finite(x):
    return x is not None and np.isfinite(x)


def mean(values):
    values = [float(v) for v in values if finite(v)]
    return float(np.mean(values)) if values else None


def mae(pred, actual):
    return mean([abs(p - a) for p, a in zip(pred, actual)])


def rmse(pred, actual):
    vals = [(p - a) ** 2 for p, a in zip(pred, actual) if finite(p) and finite(a)]
    return float(math.sqrt(np.mean(vals))) if vals else None


def normal_cdf(value):
    return 0.5 * (1.0 + math.erf(value / math.sqrt(2.0)))


def signed_power(value, alpha):
    if abs(value) < 1e-15:
        return 0.0
    return math.copysign(abs(value) ** alpha, value)


def ridge_fit(x, y, ridge_lambda=RIDGE_LAMBDA):
    x = np.asarray(x, dtype=float)
    y = np.asarray(y, dtype=float)

    means = x.mean(axis=0)
    stds = x.std(axis=0)
    stds[stds < 1e-9] = 1.0

    z = (x - means) / stds
    design = np.column_stack([np.ones(len(z)), z])

    penalty = np.eye(design.shape[1]) * ridge_lambda
    penalty[0, 0] = 0.0

    coefs = np.linalg.solve(
        design.T @ design + penalty,
        design.T @ y,
    )

    return {
        "means": means,
        "stds": stds,
        "coefs": coefs,
    }


def ridge_predict(model, x):
    x = np.asarray(x, dtype=float)
    z = (x - model["means"]) / model["stds"]
    design = np.concatenate([[1.0], z])
    return float(design @ model["coefs"])


def blended_metric(row, side, metric):
    """
    Use leakage-safe same-season pregame information when available.
    Otherwise fall back to previous-season prior.

    This is deterministic and uses only columns already generated by the
    audited historical builder.
    """
    current = row.get(f"{side}_pregame_{metric}")
    previous = row.get(f"{side}_prev_season_{metric}")

    if finite(current):
        return float(current)
    if finite(previous):
        return float(previous)
    return None


def raw_team_vector(row, offense_side, defense_side):
    """
    Team-score perspective:
    offense metrics come from offense_side.
    opponent defensive metrics come from defense_side.
    """
    off_names = [
        "off_epa",
        "off_success_rate",
        "off_explosive_rate",
        "off_pass_epa",
        "off_rush_epa",
        "havoc_allowed_rate",
        "line_yards_per_rush",
        "scoring_opp_rate",
        "drives",
        "plays_per_drive",
    ]
    def_names = [
        "def_epa_allowed",
        "def_success_allowed",
        "def_explosive_allowed",
        "def_pass_epa_allowed",
        "def_rush_epa_allowed",
        "def_havoc_created_rate",
        "def_line_yards_allowed",
        "def_scoring_opp_allowed",
    ]

    values = []
    for name in off_names:
        values.append(blended_metric(row, offense_side, name))
    for name in def_names:
        values.append(blended_metric(row, defense_side, name))

    return values


def strength_components(row, offense_side, defense_side):
    """
    Small interpretable strength summary for nonlinear matchup interaction.
    Positive offense_strength means stronger offense.
    Positive defense_strength means tougher defense.
    """
    off_epa = blended_metric(row, offense_side, "off_epa")
    off_success = blended_metric(row, offense_side, "off_success_rate")
    off_explosive = blended_metric(row, offense_side, "off_explosive_rate")

    def_epa_allowed = blended_metric(row, defense_side, "def_epa_allowed")
    def_success_allowed = blended_metric(row, defense_side, "def_success_allowed")
    def_explosive_allowed = blended_metric(row, defense_side, "def_explosive_allowed")

    vals = [
        off_epa, off_success, off_explosive,
        def_epa_allowed, def_success_allowed, def_explosive_allowed,
    ]
    if not all(finite(v) for v in vals):
        return None

    offense_strength = (
        float(off_epa)
        + 0.75 * float(off_success)
        + 0.50 * float(off_explosive)
    )
    # Lower allowed is better, so negate allowed values.
    defense_strength = -(
        float(def_epa_allowed)
        + 0.75 * float(def_success_allowed)
        + 0.50 * float(def_explosive_allowed)
    )
    return offense_strength, defense_strength


def team_feature_vector(row, offense_side, defense_side, is_home, alpha):
    raw = raw_team_vector(row, offense_side, defense_side)
    if not all(finite(v) for v in raw):
        return None

    strength = strength_components(row, offense_side, defense_side)
    if strength is None:
        return None

    offense_strength, opponent_defense_strength = strength
    advantage = offense_strength - opponent_defense_strength

    possessions = blended_metric(row, offense_side, "drives")
    if not finite(possessions):
        return None

    return [
        *[float(v) for v in raw],
        float(offense_strength),
        float(opponent_defense_strength),
        float(advantage),
        float(signed_power(advantage, alpha)),
        float(advantage * possessions),
        float(possessions),
        1.0 if is_home else -1.0,
    ]


def control_feature_vector(row):
    """
    Linear home-minus-away margin control using the same audited feature base.
    No nonlinear term and no market inputs.
    """
    values = []
    for metric in METRICS:
        home = blended_metric(row, "home", metric)
        away = blended_metric(row, "away", metric)
        if not finite(home) or not finite(away):
            return None
        values.append(float(home - away))

    # Venue data is not available in this table. We preserve a constant home
    # indicator for the control, matching the score engine's home/away indicator.
    values.append(1.0)
    return values


def eligible_rows(df):
    rows = []
    for _, row in df.iterrows():
        h = team_feature_vector(row, "home", "away", True, 2.0)
        a = team_feature_vector(row, "away", "home", False, 2.0)
        c = control_feature_vector(row)
        if h is None or a is None or c is None:
            continue
        rows.append(row)
    return pd.DataFrame(rows)


def fit_score_engine(training, alpha):
    x = []
    y = []

    for _, row in training.iterrows():
        home_vec = team_feature_vector(row, "home", "away", True, alpha)
        away_vec = team_feature_vector(row, "away", "home", False, alpha)
        if home_vec is None or away_vec is None:
            continue

        x.append(home_vec)
        y.append(float(row["home_score"]))
        x.append(away_vec)
        y.append(float(row["away_score"]))

    if len(x) < 100:
        raise RuntimeError("Too few team-score training rows.")

    model = ridge_fit(x, y)
    model["alpha"] = alpha
    return model


def predict_score_engine(model, row):
    alpha = model["alpha"]
    h = team_feature_vector(row, "home", "away", True, alpha)
    a = team_feature_vector(row, "away", "home", False, alpha)

    if h is None or a is None:
        return None

    home = max(0.0, ridge_predict(model, h))
    away = max(0.0, ridge_predict(model, a))
    return home, away


def fit_control(training):
    x = []
    y = []

    for _, row in training.iterrows():
        vec = control_feature_vector(row)
        if vec is None:
            continue
        x.append(vec)
        y.append(float(row["actual_home_margin"]))

    if len(x) < 100:
        raise RuntimeError("Too few control training rows.")

    return ridge_fit(x, y)


def predict_control(model, row):
    vec = control_feature_vector(row)
    if vec is None:
        return None
    return ridge_predict(model, vec)


def select_alpha(records):
    folds = [
        (list(range(2019, 2023)), 2023),
        (list(range(2019, 2024)), 2024),
    ]

    table = []

    for alpha in ALPHA_CANDIDATES:
        fold_rmse = []

        for train_years, val_year in folds:
            train = records[records["season"].isin(train_years)]
            val = records[records["season"] == val_year]

            model = fit_score_engine(train, alpha)

            pred = []
            actual = []
            for _, row in val.iterrows():
                scores = predict_score_engine(model, row)
                if scores is None:
                    continue
                pred.append(scores[0] - scores[1])
                actual.append(float(row["actual_home_margin"]))

            fold_rmse.append(rmse(pred, actual))

        table.append({
            "alpha": alpha,
            "fold_rmse": fold_rmse,
            "mean_inner_rmse": mean(fold_rmse),
        })

    winner = min(table, key=lambda r: r["mean_inner_rmse"])
    return float(winner["alpha"]), table


def fit_probability_scale(training, model):
    residuals = []

    for _, row in training.iterrows():
        scores = predict_score_engine(model, row)
        if scores is None:
            continue
        residuals.append(
            float(row["actual_home_margin"]) - (scores[0] - scores[1])
        )

    base_std = float(np.std(residuals))

    market = training[training["market_home_spread"].notna()]

    best = None
    for scale in np.arange(1.0, 4.01, 0.05):
        brier = []

        for _, row in market.iterrows():
            scores = predict_score_engine(model, row)
            if scores is None:
                continue

            spread = float(row["market_home_spread"])
            actual_cover_margin = float(row["actual_home_margin"]) + spread
            if abs(actual_cover_margin) < 1e-9:
                continue

            predicted_margin = scores[0] - scores[1]
            market_margin = -spread
            edge = predicted_margin - market_margin
            prob = normal_cdf(edge / (base_std * scale))
            actual = 1.0 if actual_cover_margin > 0 else 0.0
            brier.append((prob - actual) ** 2)

        if not brier:
            continue

        score = float(np.mean(brier))
        if best is None or score < best["brier"]:
            best = {"scale": float(scale), "brier": score}

    if best is None:
        return base_std, 1.0, None

    return base_std, best["scale"], best["brier"]


def favorite_bucket_report(scored):
    buckets = [
        (0, 3, "0-3"),
        (3, 7, "3-7"),
        (7, 14, "7-14"),
        (14, 21, "14-21"),
        (21, 28, "21-28"),
        (28, 40, "28-40"),
        (40, 999, "40+"),
    ]

    out = []

    for low, high, label in buckets:
        games = [
            g for g in scored
            if g.get("market_favorite_size") is not None
            and low <= g["market_favorite_size"] < high
        ]

        if not games:
            out.append({"range": label, "games": 0})
            continue

        actual_oriented = []
        control_oriented = []
        score_oriented = []

        for g in games:
            home_favorite = g["market_home_spread"] < 0
            sign = 1.0 if home_favorite else -1.0

            actual_oriented.append(sign * g["actual_home_margin"])
            control_oriented.append(sign * g["control_margin"])
            score_oriented.append(sign * g["score_engine_margin"])

        out.append({
            "range": label,
            "games": len(games),
            "control_mae": mae(control_oriented, actual_oriented),
            "score_engine_mae": mae(score_oriented, actual_oriented),
            "control_bias": mean([
                p - a for p, a in zip(control_oriented, actual_oriented)
            ]),
            "score_engine_bias": mean([
                p - a for p, a in zip(score_oriented, actual_oriented)
            ]),
        })

    return out


def probability_bins(scored):
    bins = [
        (0.00, 0.45, "0-45%"),
        (0.45, 0.55, "45-55%"),
        (0.55, 0.65, "55-65%"),
        (0.65, 0.75, "65-75%"),
        (0.75, 1.01, "75%+"),
    ]

    out = []
    for low, high, label in bins:
        games = [
            g for g in scored
            if g.get("home_cover_probability") is not None
            and g.get("actual_home_cover") is not None
            and low <= g["home_cover_probability"] < high
        ]
        out.append({
            "range": label,
            "games": len(games),
            "avg_predicted_home_cover": (
                mean([g["home_cover_probability"] for g in games])
                if games else None
            ),
            "actual_home_cover_rate": (
                mean([g["actual_home_cover"] for g in games])
                if games else None
            ),
        })
    return out


def round_tree(value):
    if isinstance(value, dict):
        return {k: round_tree(v) for k, v in value.items()}
    if isinstance(value, list):
        return [round_tree(v) for v in value]
    if isinstance(value, (float, np.floating)):
        if not np.isfinite(value):
            return None
        return round(float(value), 6)
    if isinstance(value, (np.integer,)):
        return int(value)
    return value


def main():
    if not AUDIT.exists():
        raise SystemExit("Historical training audit is missing.")

    audit = json.loads(AUDIT.read_text(encoding="utf-8"))
    if audit.get("status") != "PASS":
        raise SystemExit("Historical training audit must PASS before sealed test.")

    df = pd.read_csv(DATA)

    # Absolute sealed split.
    training_all = df[df["season"].isin(TRAIN_YEARS)].copy()
    testing_all = df[df["season"] == TEST_YEAR].copy()

    training = eligible_rows(training_all)
    testing = eligible_rows(testing_all)

    if testing.empty:
        raise RuntimeError("No eligible sealed 2025 rows.")

    print("Selecting nonlinear alpha using 2019-2024 inner OOS only...")
    selected_alpha, alpha_table = select_alpha(training)

    print("Fitting final score engine on 2019-2024...")
    score_model = fit_score_engine(training, selected_alpha)

    print("Fitting linear margin control on 2019-2024...")
    control_model = fit_control(training)

    print("Fitting probability calibration on 2019-2024 only...")
    residual_std, probability_scale, train_brier = fit_probability_scale(
        training,
        score_model,
    )

    print("Opening sealed 2025...")
    scored = []

    for _, row in testing.iterrows():
        scores = predict_score_engine(score_model, row)
        control_margin = predict_control(control_model, row)

        if scores is None or control_margin is None:
            continue

        home_score, away_score = scores
        score_margin = home_score - away_score

        record = {
            "game_id": int(row["game_id"]),
            "week": int(row["week"]),
            "home_team": row["home_team"],
            "away_team": row["away_team"],
            "actual_home_score": float(row["home_score"]),
            "actual_away_score": float(row["away_score"]),
            "actual_home_margin": float(row["actual_home_margin"]),
            "actual_total": float(row["actual_total"]),
            "control_margin": float(control_margin),
            "score_engine_home_score": float(home_score),
            "score_engine_away_score": float(away_score),
            "score_engine_margin": float(score_margin),
            "score_engine_total": float(home_score + away_score),
            "market_home_spread": (
                float(row["market_home_spread"])
                if pd.notna(row["market_home_spread"])
                else None
            ),
            "market_total": (
                float(row["market_total"])
                if pd.notna(row["market_total"])
                else None
            ),
        }

        if record["market_home_spread"] is not None:
            spread = record["market_home_spread"]
            market_margin = -spread
            edge = score_margin - market_margin
            home_prob = normal_cdf(
                edge / (residual_std * probability_scale)
            )
            cover_margin = record["actual_home_margin"] + spread

            record["model_edge_vs_market"] = float(edge)
            record["home_cover_probability"] = float(home_prob)
            record["selected_cover_probability"] = float(
                max(home_prob, 1.0 - home_prob)
            )
            record["actual_home_cover"] = (
                None
                if abs(cover_margin) < 1e-9
                else (1.0 if cover_margin > 0 else 0.0)
            )
            record["market_favorite_size"] = abs(market_margin)

        scored.append(record)

    control_pred = [g["control_margin"] for g in scored]
    score_pred = [g["score_engine_margin"] for g in scored]
    actual_margin = [g["actual_home_margin"] for g in scored]

    score_home = [g["score_engine_home_score"] for g in scored]
    score_away = [g["score_engine_away_score"] for g in scored]
    actual_home = [g["actual_home_score"] for g in scored]
    actual_away = [g["actual_away_score"] for g in scored]

    totals_pred = [g["score_engine_total"] for g in scored]
    totals_actual = [g["actual_total"] for g in scored]

    market_games = [
        g for g in scored
        if g.get("market_home_spread") is not None
        and g.get("actual_home_cover") is not None
    ]

    brier_2025 = mean([
        (g["home_cover_probability"] - g["actual_home_cover"]) ** 2
        for g in market_games
    ])

    report = {
        "status": "SEALED_COMPLETE",
        "dataset": "historical_training_v3_sportsdataverse_espn",
        "train_years": TRAIN_YEARS,
        "test_year": TEST_YEAR,
        "leakage_audit": {
            "historical_training_audit_status": audit.get("status"),
            "alpha_selected_without_2025": True,
            "model_fit_without_2025": True,
            "probability_calibration_without_2025": True,
            "market_spread_used_as_predictive_feature": False,
            "sealed_2025_opened_only_after_training": True,
        },
        "important_scope_note": (
            "Control is a same-dataset linear margin ridge benchmark, not the "
            "exact live production SP+/curated-HFA model. The SportsDataverse "
            "historical table does not contain all live production inputs."
        ),
        "venue_limitation": (
            "Neutral-site metadata is unavailable in this canonical table. "
            "The experiment uses a symmetric home/away indicator and does not "
            "claim curated team-specific historical HFA."
        ),
        "training_rows": int(len(training)),
        "sealed_2025_rows": int(len(scored)),
        "selected_alpha": selected_alpha,
        "alpha_inner_validation": alpha_table,
        "ridge_lambda": RIDGE_LAMBDA,
        "probability_calibration": {
            "training_residual_std": residual_std,
            "selected_scale": probability_scale,
            "training_brier": train_brier,
            "sealed_2025_brier": brier_2025,
        },
        "overall": {
            "control_margin_mae": mae(control_pred, actual_margin),
            "score_engine_margin_mae": mae(score_pred, actual_margin),
            "control_margin_rmse": rmse(control_pred, actual_margin),
            "score_engine_margin_rmse": rmse(score_pred, actual_margin),
            "score_engine_team_score_mae": mean(
                [abs(p-a) for p, a in zip(score_home, actual_home)]
                + [abs(p-a) for p, a in zip(score_away, actual_away)]
            ),
            "score_engine_total_mae": mae(totals_pred, totals_actual),
            "score_engine_total_rmse": rmse(totals_pred, totals_actual),
        },
        "favorite_size_buckets": favorite_bucket_report(scored),
        "probability_bins": probability_bins(scored),
        "market_note": (
            "Historical spread is used only as an evaluation benchmark. "
            "This dataset does not preserve timestamped open/current/close "
            "snapshots, so this report does NOT claim historical CLV."
        ),
        "games": scored,
    }

    # Mechanical promotion read, not a betting recommendation.
    margin_mae_better = (
        report["overall"]["score_engine_margin_mae"]
        < report["overall"]["control_margin_mae"]
    )
    margin_rmse_better = (
        report["overall"]["score_engine_margin_rmse"]
        < report["overall"]["control_margin_rmse"]
    )

    tail = {
        r["range"]: r
        for r in report["favorite_size_buckets"]
    }
    tail_improvements = []
    for label in ["21-28", "28-40", "40+"]:
        row = tail.get(label, {})
        if row.get("games", 0) > 0:
            c = row.get("control_bias")
            s = row.get("score_engine_bias")
            if finite(c) and finite(s):
                tail_improvements.append(abs(s) < abs(c))

    report["decision"] = {
        "score_engine_margin_mae_better": margin_mae_better,
        "score_engine_margin_rmse_better": margin_rmse_better,
        "large_favorite_bias_improved_in_all_available_21plus_buckets": (
            all(tail_improvements) if tail_improvements else None
        ),
        "promotion_status": (
            "CANDIDATE_FOR_WEEK1_REVIEW"
            if margin_mae_better and margin_rmse_better
            else "HOLD_CONTROL"
        ),
        "note": (
            "Promotion status is a model-development gate only. "
            "It is not a claim of guaranteed betting profitability."
        ),
    }

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        json.dumps(round_tree(report), indent=2),
        encoding="utf-8",
    )

    print("=" * 78)
    print("SEALED 2025 SCORE ENGINE TEST COMPLETE")
    print("=" * 78)
    print("Training rows:", len(training))
    print("Sealed rows:", len(scored))
    print("Selected alpha:", selected_alpha)
    print(
        "Control margin MAE / RMSE:",
        round(report["overall"]["control_margin_mae"], 4),
        "/",
        round(report["overall"]["control_margin_rmse"], 4),
    )
    print(
        "Score Engine margin MAE / RMSE:",
        round(report["overall"]["score_engine_margin_mae"], 4),
        "/",
        round(report["overall"]["score_engine_margin_rmse"], 4),
    )
    print(
        "Score Engine team-score MAE:",
        round(report["overall"]["score_engine_team_score_mae"], 4),
    )
    print(
        "Score Engine total MAE:",
        round(report["overall"]["score_engine_total_mae"], 4),
    )
    print("Decision:", report["decision"]["promotion_status"])
    print("Wrote:", OUT.relative_to(ROOT))


if __name__ == "__main__":
    main()
